### ISSUE TITLE
Skill Issue

### ISSUE THREAD

**Issue by chairclr** [CEO-Chair/HeadlessTerrariaClient#1]
Leave a comment

**Comment by yayakame** [comment]
omg so true!!!!!!!!!!!!!!

**Comment by chairclr** [comment]
not enough skill :(

**Comment by SomeoneTN** [comment]
### Comments regarding the skill issues

I have a large amount of much more important things to worry about and as such, worrying about my skill issues is gay. After seeing this however, I am now questioning whether I am worthy or not and it is causing me a lot of stress.

After a few days of needlessly worrying about such unimportant things, I have come to the conclusion that I will have to _get good_.

Also, here is [Chese](https://www.youtube.com/watch?v=j8Ih_3Y2juw).

I wish you all a nice morning, afternoon, & evening.

**Comment by chairclr** [comment]
hi

**Comment by somegooseguy** [comment]
ok

**Comment by chairclr** [comment]
this is true

**Comment by SomeoneTN** [comment]
I shid myself

**Comment by chairclr** [comment]
i think theres an issue with skill

**Comment by SomeoneTN** [comment]
Are you okay Chair? It's okay bro you can talk with us.
We're here for you buddy, we're your friends.

**Comment by chairclr** [comment]
yeah im fine but there seems to be an issue with the skill ofr this client and it's not really a good thing because they don't know if I have a good way to get it done before you get home and I don't know

**Comment by chairclr** [comment]
any skills isues?
