### ISSUE TITLE
You left the Forums

### ISSUE THREAD

**Issue by oz5581** [CEO-Chair/HeadlessTerrariaClient#10]
Greetings CEO-Chair, We are sorry to see you have left the Forums Community (Terraform)
Here are the most frequent commonly asked Questions:
- Will you ever return to raid the Forums?
- Are you going to start raiding servers?
- Are you building up a small community of server raiders?
- Do you now affiliate with people who raid servers?
- Did you release your Terraria Client so other people can raid servers?
- Is the 'Headless' Client's Intent now for raiding servers?

**Comment by chairclr** [comment]
1. No
2. No
3. No
4. No
5. No
6. No
The reason I left Terraform's discord server is because I left every server I was in

**Comment by steviegt6** [comment]
awesome issue!
